version: "3"

services:
  swic2_africa:
    image: africahazardswatch.org/swic2-africa
    container_name: swic2_africa
    build: .
    restart: ${RESTART_POLICY}
    environment:
      - PORT=${PORT}
    ports:
      - ${PORT}:3000

networks:
    default:
      name:  ${AHW_DOCKER_NETWORK}
      external: true